dev-server/containers/MainView/index.js
src/components/NavigationBar/index.js
src/components/NavigationBar/styles.scss

support show notice counts on navigation button

support show notice counts on navigation button

---

.travis.yml
README.md
gulpfile.js
package.json
scripts/prepare_release.sh
scripts/start_release.sh

travis auto publish to npm when tag
package version will be same as tag

travis auto publish to npm when tag

---

dev-server/Phone.js
dev-server/containers/App/index.js
dev-server/containers/AppView/index.js
dev-server/containers/MainView/index.js
src/components/ComposeTextPanel/i18n/en-US.js
src/components/ComposeTextPanel/i18n/index.js
src/components/ComposeTextPanel/i18n/loadLocale.js
src/components/ComposeTextPanel/index.js
src/components/ComposeTextPanel/styles.scss
src/components/ContactDropdownList/i18n/en-US.js
src/components/ContactDropdownList/i18n/index.js
src/components/ContactDropdownList/i18n/loadLocale.js
src/components/ContactDropdownList/index.js
src/components/ContactDropdownList/styles.scss
src/components/MessageSenderAlert/i18n/en-US.js
src/components/MessageSenderAlert/i18n/index.js
src/components/MessageSenderAlert/i18n/loadLocale.js
src/components/MessageSenderAlert/index.js
src/components/RecipientsInput/index.js
src/components/RecipientsInput/styles.scss
src/components/RemoveButton/index.js
src/components/RemoveButton/styles.scss
src/containers/ComposeTextPage/index.js

add compose text page

---

dev-server/Phone.js
dev-server/containers/App/index.js
dev-server/containers/MainView/index.js
package.json
src/components/ComposeTextPanel/index.js
src/components/ContactDropdownList/index.js
src/components/ContactDropdownList/styles.scss
src/components/ConversationMessageList/index.js
src/components/ConversationMessageList/styles.scss
src/components/ConversationPanel/i18n/en-US.js
src/components/ConversationPanel/i18n/index.js
src/components/ConversationPanel/i18n/loadLocale.js
src/components/ConversationPanel/index.js
src/components/ConversationPanel/styles.scss
src/components/RecipientsHeader/index.js
src/components/RecipientsHeader/styles.scss
src/components/RemoveButton/index.js
src/containers/ConversationPage/index.js

add conversation page

---

src/components/CallingSettingsPanel/index.js
src/components/RegionSettingsPanel/index.js
src/components/RegionSettingsPanel/styles.scss

remove  condition which check the count of availableCountries; replace select to component

fix RCINT-3513: country list should be shown even only one dialing plan

---

dev-server/containers/MainView/index.js
src/assets/DynamicsFont/DynamicsFont.scss
src/assets/DynamicsFont/style.css
src/components/ComposeTextPanel/i18n/en-US.js
src/components/ComposeTextPanel/index.js
src/components/ComposeTextPanel/styles.scss
src/components/MessageSenderAlert/i18n/en-US.js
src/containers/MessagesPage/index.js

update messages hover icon #99 
remove messages and compose text header #101 
change sms text empty warning method #92

enhance messages related page

---

src/containers/ConversationPage/index.js

not sync message when open conversation page #94

not sync message when open conversation page

---

src/containers/ConversationPage/index.js

refactor conversation page - no connect module object

refactor conversation page - no connect module object

---

dev-server/Phone.js
src/components/MessageItem/index.js
src/components/MessageList/index.js
src/components/MessageList/styles.scss
src/containers/MessagesPage/index.js
src/containers/MessagesPage/styles.scss

remove unused loading #98 
increase perPage to show scroller
not connect module object to component

refactor messages page

---

dev-server/Phone.js
dev-server/containers/App/index.js
dev-server/containers/AppView/index.js
src/components/ConnectivityAlert/i18n/en-US.js
src/components/ConnectivityAlert/i18n/index.js
src/components/ConnectivityAlert/i18n/loadLocale.js
src/components/ConnectivityAlert/index.js
src/components/OfflineModeBadge/i18n/en-US.js
src/components/OfflineModeBadge/i18n/index.js
src/components/OfflineModeBadge/i18n/loadLocale.js
src/components/OfflineModeBadge/index.js
src/components/OfflineModeBadge/styles.scss
src/components/RateExceededAlert/i18n/en-US.js
src/components/RateExceededAlert/i18n/index.js
src/components/RateExceededAlert/i18n/loadLocale.js
src/components/RateExceededAlert/index.js

add offline mode badge

---

dev-server/containers/App/index.js
dev-server/containers/AppView/index.js
src/components/AlertDisplay/index.js
src/components/AlertDisplay/styles.scss
src/containers/AlertContainer/index.js
src/containers/WelcomePage/index.js
src/containers/WelcomePage/styles.scss

adjust alert style #111 
move alert display from AppView to MainView
add alert display to WelcomePage
add AlertContainer

adjust alert ui

---

src/components/ComposeTextPanel/index.js
src/components/ComposeTextPanel/styles.scss
src/components/RecipientsInput/index.js

remove sender setting show icon
support add recipient to toNumbers by comma/semicolon or Enter

enhancement compose text page

---

src/components/AlertDisplay/styles.scss
src/components/OfflineModeBadge/styles.scss
src/containers/AlertContainer/index.js

it fail when import container from release

bugfix for import components dir in alert container

---

src/components/ComposeTextPanel/styles.scss
src/components/ConversationPanel/index.js
src/components/ConversationPanel/styles.scss
src/components/MessageItem/styles.scss
src/components/MessageList/index.js
src/components/MessageList/styles.scss
src/components/OfflineModeBadge/styles.scss
src/components/SearchInput/index.js
src/components/SearchInput/styles.scss
src/containers/ComposeTextPage/index.js

fix some ui bug caused by box-sizing that found in dynamics
adjust style of message related page
disable send message button when text is empty

adjust sms related page ui

---

dev-server/Phone.js
package.json
src/components/ComposeTextPanel/index.js
src/components/ContactDropdownList/index.js
src/components/ConversationPanel/index.js
src/components/ConversationPanel/styles.scss
src/components/RecipientsInput/index.js
src/containers/ComposeTextPage/index.js

not format to number on Recipients Input

not format to number on Recipients Input

---

package.json

rename ringcentral-js-widget to ringcentral-widget

rename ringcentral-js-widget to ringcentral-widget

---

package.json
src/components/NavigationBar/index.js
src/components/NavigationBar/styles.scss
src/components/RecipientsHeader/styles.scss
src/components/RemoveButton/styles.scss
src/containers/ConversationPage/index.js
src/containers/MessagesPage/i18n/en-US.js
src/containers/MessagesPage/index.js

adjust ui style on conversation
support contact matcher in messages page
support show noticeCounts 99+

adjust ui style on conversation

---

dev-server/Phone.js
package.json
src/components/NavigationBar/styles.scss
src/containers/MessagesPage/i18n/en-CA.js
src/containers/MessagesPage/i18n/en-GB.js
yarn.lock

adjust unread messages ui
update commons version
fix typo

adjust unread messages ui

---

src/containers/MessagesPage/index.js

show matched name in message search list

show matched name in message search list

---

package.json
src/components/ComposeTextPanel/styles.scss
src/components/ConversationPanel/index.js
src/components/ConversationPanel/styles.scss
src/components/MessageItem/styles.scss
src/components/RecipientHeader/i18n/en-US.js
src/components/RecipientHeader/i18n/index.js
src/components/RecipientHeader/i18n/loadLocale.js
src/components/RecipientHeader/index.js
src/components/RecipientHeader/styles.scss
src/components/RecipientsHeader/index.js
src/components/RecipientsHeader/styles.scss
src/containers/ConversationPage/index.js
yarn.lock

show matchedNames dropdown list on conversation page

show matchedNames dropdown list on conversation page

---

src/components/ComposeTextPanel/index.js
src/components/ContactDropdownList/index.js
src/components/ContactDropdownList/styles.scss
src/components/ConversationMessageList/index.js
src/components/ConversationMessageList/styles.scss
src/components/ConversationPanel/styles.scss
src/components/RecipientHeader/i18n/en-US.js
src/components/RecipientHeader/index.js
src/components/RecipientHeader/styles.scss
src/components/RecipientsHeader/index.js
src/components/RecipientsHeader/styles.scss
src/components/RecipientsInput/index.js
src/containers/MessagesPage/index.js

adjust  conversation ui
support hot key on recipients input

Enhance conversation ui

---

src/components/DropdownSelect/index.js
src/components/DropdownSelect/styles.scss

add dropdown select component

---

src/components/RecipientsInput/index.js

It should not auto-select the first matching recorde when press semicolon and comma on keyboard

It should not auto-select the first matching record

---

src/components/CallItem/index.js
src/components/ConversationMessageList/index.js
src/components/ConversationPanel/index.js
src/components/MessageItem/index.js
src/components/MessageList/index.js
src/components/MessageList/styles.scss
src/containers/CallHistoryPage/index.js
src/containers/CallMonitorPage/index.js

rcint-4132 Cannot display the Ext number on group conversation
rcint-4137 The time is incorrect on Messages list
rcint-4138 Cannot show all conversations on messages list

add scroll to messagelist; fix name display for group conversation

---

src/components/CallItem/index.js
src/components/CallList/index.js
src/components/CallsPanel/index.js
src/components/ContactDisplay/index.js
src/components/ConversationPanel/index.js
src/components/MessageItem/index.js
src/containers/CallHistoryPage/index.js
src/containers/CallMonitorPage/index.js
src/containers/ConversationPage/index.js
src/containers/MessagesPage/index.js

not to fallback to RC contact name and pass entity name or phone number to receiver

rcint-4159 rcint-4192 

---

dev-server/containers/App/index.js
package.json
src/components/CallItem/index.js
src/components/CallItem/styles.scss
src/components/DropdownSelect/index.js
src/components/MessageItem/index.js
src/components/MessageList/index.js
src/components/MessageList/styles.scss
src/containers/CallHistoryPage/index.js
src/containers/CallMonitorPage/index.js

add contactSearch for clickToSMS;
fix active call color;
fix message scroll;
fix format phoneNumber as entityName

fix bugs related to messages

---

src/components/CallItem/styles.scss
src/components/ContactDisplay/index.js
src/components/ContactDisplay/styles.scss
src/components/ConversationPanel/styles.scss
src/components/DropdownSelect/index.js
src/components/DropdownSelect/styles.scss
src/components/MessageItem/index.js
src/components/MessageItem/styles.scss
src/components/RegionSettingsPanel/index.js

rcint-4038 Show phone number together with entity name when on hover an entity on History/Message/Active Calls tab
rcint-4204 fix dropdown list problems on Conversation detail

hover on entity

---

dev-server/containers/MainView/index.js

hidden conference if no permission

hidden conference if no permission

---

src/components/CallIdSelect/i18n/en-US.js

Feature enhance calling setting

enhance of calling setting

---

dev-server/Phone.js
src/components/ComposeTextPanel/index.js
src/components/ComposeTextPanel/styles.scss
src/components/DropdownSelect/index.js
src/components/DropdownSelect/styles.scss

use dropdown select on sms sender select
update SDK cache prefix

use dropdown select on sms sender select

---

.travis.yml
scripts/prepare_release.sh

build Github Pages on CI

---

dev-server/webpack.config.js
docs/package.json
docs/postcss.config.js
docs/webpack-dev-server.config.js
docs/webpack-production.config.js
docs/yarn.lock
package.json
src/assets/images/ActivityCall.svg
src/assets/images/Add.svg
src/assets/images/AddCall.svg
src/assets/images/AddContact.svg
src/assets/images/Answer.svg
src/assets/images/ContactDetail.svg
src/assets/images/Dialpad.svg
src/assets/images/End.svg
src/assets/images/Fax.svg
src/assets/images/Flip.svg
src/assets/images/Forward.svg
src/assets/images/HideDialpad.svg
src/assets/images/Hold.svg
src/assets/images/Ignore.svg
src/assets/images/Message.svg
src/assets/images/MessageFill.svg
src/assets/images/Mute.svg
src/assets/images/Park.svg
src/assets/images/Play.svg
src/assets/images/Record.svg
src/assets/images/Transfer.svg
src/assets/images/Unmute.svg
src/assets/images/Voicemail.svg

remove SVG icon title
fix docs page build fail

remove SVG icon title

---

scripts/prepare_release.sh

remove wrong comment

---

docs/src/app/pages/Components/ContactDisplay/Demo.js
docs/src/app/pages/Components/ContactDropdownList/Demo.js
docs/src/app/pages/Components/ConversationMessageList/Demo.js
docs/src/app/pages/Components/DialTextInput/Demo.js
docs/src/app/pages/Components/DialerPanel/Demo.js

ContactDisplay, ContactDropdownList, ConversationMessageList, DialerTextInput, DialerPanel

fix showcase 

---

docs/src/app/pages/Components/ContactDisplay/Demo.js
docs/src/app/pages/Components/ContactDropdownList/Demo.js
docs/src/app/pages/Components/ContactDropdownList/styles.scss
docs/src/app/pages/Components/ConversationMessageList/Demo.js
docs/src/app/pages/Components/DialTextInput/Demo.js
docs/src/app/pages/Components/DialerPanel/Demo.js
docs/src/app/pages/Components/DialerPanel/styles.scss

Showcase 01

---

src/components/FormattedMessage/index.js

fix invalid tag error in alert message

---

dev-server/containers/App/index.js
src/components/CallIdSelect/i18n/en-US.js

support AdditionalCompanyNumber in CallIdSelect

support AdditionalCompanyNumber in CallIdSelect

---

src/components/ActiveCallDialPad/index.js

fix 'extension can not be recognized when make a outgoing call'

fix 'extension can not be recognized when make a outgoing call'

---

dev-server/Phone.js
src/containers/ActiveCallPage/index.js

clean avatar when session change

clean avatar when session change

---

dev-server/containers/App/index.js
src/containers/DialerPage/index.js

disable dialer button when connecting web phone

disable dialer button when connecting web phone

---

docs/src/app/componentsData.json
docs/src/app/pages/Components/ActiveCallPanel/Demo.js
docs/src/app/pages/Components/IncomingCallPanel/Demo.js
package.json
src/components/ActiveCallPanel/index.js
src/components/IncomingCallPanel/index.js
yarn.lock

fix show case page error on incoming call page and active call page

---

src/components/ActiveCallPad/styles.scss

adjust active call pad ui

---

package.json
src/components/ContactDisplay/index.js
src/containers/CallCtrlPage/index.js
yarn.lock

remove stopPropagation

---

src/components/Draggable/index.js

fix onClick problem on Draggable

---

dev-server/containers/App/index.js
src/components/ActiveCallItem/index.js
src/components/ActiveCallsPanel/index.js
src/containers/ActiveCallsPage/index.js

enable to redirect when calls list is empty
call `reject` function when `toVoicemail` doesn't get responses.

enable to redirect when calls list is empty

---

src/components/ActiveCallDialPad/index.js

support to paste and type on Keypad

---

src/components/ConferencePanel/i18n/loadLocale.js
yarn.lock

This would allow browser locale 'jp' to default to load 'jp-JP'

update locale-loader to 0.3.5 and fix a loader file error

---

src/components/ActiveCallBadge/styles.scss
src/components/ConversationMessageList/styles.scss

Fix badge index problem
Fix conversation ui problem, fix [word break problem](https://github.com/ringcentral/ringcentral-web-widget/issues/44)

fix conversation page ui problem

---

src/components/ConferencePanel/index.js
src/components/ConferencePanel/styles.scss

Fix color for other brand
Fix checkbox style
Fix scrollable area

Fix style issues

---

src/components/ActionMenuList/styles.scss
src/components/VoicemailPlayer/i18n/en-US.js
src/components/VoicemailPlayer/index.js
src/components/VoicemailPlayer/styles.scss

adjust voicemail ui

---

src/components/ConferencePanel/index.js
src/containers/ConferencePage/index.js

Add city for conference dial-in number

Conference bug fix and new feature

---

.editorconfig
.gitattributes
.vscode/settings.json

Added config for eol to make sure it keeps consistent across OS

enforce eol format to lf

---

src/containers/MessagesPage/index.js

* add canNotViewContact prop to hide the extension button

feat(MessagesPage): add canNotViewContact prop

---

src/components/CallItem/styles.scss

* fix scrollbar of calls tab doesn't display well in safari

fix scrollbar in safari

---

src/components/SpinnerOverlay/styles.scss

fix https://github.com/ringcentral/ringcentral-js-widgets/issues/631

add SpinnerOverlay z-index

---

src/containers/ConferencePage/i18n/en-US.js

add missing country name: Colombia

fix(en-US.js): add

---

packages/ringcentral-integration/modules/Softphone/index.js

add window.navigator.mslaunchUri to support ie for ie will block launching programs

---

packages/ringcentral-widgets/components/AudioSettingsPanel/i18n/en-US.js
packages/ringcentral-widgets/components/AudioSettingsPanel/index.js

Include audio settings
https://jira.ringcentral.com/browse/RCINT-7318

audio settings improvement

---

packages/ringcentral-widgets/lib/AdapterCore/index.js

since the close button may not be there in some cases.

minor: make close button optional in AdpterCore

---

packages/ringcentral-integration/modules/Auth/index.js
packages/ringcentral-widgets/components/DatePicker/index.js

1# TOKEN REVOKE
2# DATE PICKER TEXT MODIFY

1# TOKEN REVOKE 2# DATE PICKER TEXT MODIFY

---

packages/ringcentral-integration/modules/Conference/index.js
packages/ringcentral-integration/modules/ExtensionDevice/index.js
packages/ringcentral-integration/modules/ExtensionPhoneNumber/index.js
packages/ringcentral-integration/modules/ForwardingNumber/index.js

remove uri

---

packages/ringcentral-integration/lib/DataMatcher/index.js
packages/ringcentral-integration/lib/SynchronizedStorage.js
packages/ringcentral-integration/modules/CallHistory/index.js
packages/ringcentral-integration/modules/CallMonitor/index.js
packages/ringcentral-integration/modules/ContactSearch/index.js
packages/ringcentral-integration/modules/Messages/index.js
packages/ringcentral-integration/modules/Webphone/index.js
packages/ringcentral-widgets-demo/dev-server/Phone.js
packages/ringcentral-widgets/containers/ActiveCallsPage/index.js

* in handling storage events
* Add TabManager support to all modules that may rely on DataMatchers

[bug] Modify SynchronizedStorage's logic

---

packages/ringcentral-integration/modules/Conversation/getConversationReducer.js

http://ec2-13-124-226-35.ap-northeast-2.compute.amazonaws.com/sentry/skypeforbusiness/issues/490/

fix bug from sentry

---

packages/ringcentral-widgets/components/ActiveCallPad/index.js

rcint-7837(mute button should be disabled when user hold the call)

mute button should be disabled when user hold the call

---

packages/ringcentral-widgets/components/ActiveCallItem/index.js
packages/ringcentral-widgets/components/CallItem/index.js

fix bug that throw error in parseinfo when phonenumber is null when anonymous call

---

packages/ringcentral-integration/integration-test/spec-modules/accountExtension.js
packages/ringcentral-integration/integration-test/spec-modules/composeText.js

Update integration tests for new test environment

fix integration tests

---

packages/ringcentral-integration/lib/di/utils/is_type.js

fix scenario when input is null

fix(is_type): fix object type checking

---

packages/ringcentral-integration/modules/Webphone/index.js
packages/ringcentral-widgets-cli/package.json
packages/ringcentral-widgets-cli/templates/Project/package-template.json

remove unuse extension device dependency from webphone
Update cli

remove unuse extension device dependency from webphone

---

packages/ringcentral-integration/modules/CallMonitor/index.js

bug fixes(when user call to an sfb contacts,then add a call.The simplified call control will not display the sfb contact's name)

rcint-8089 bug fixes

---

packages/ringcentral-widgets/components/CallAvatar/index.js

I remember fixing this issue on branch RCINT-7708, maybe there is a sync-up issue when merging back the master

fix(CallAvatar): add componentWillUnmount

---

packages/ringcentral-widgets/components/ActiveCallPanel/MergeInfo.js

avoid the lastcallinfo is null

Rcint-8114

---

packages/ringcentral-widgets/components/DialerPanel/styles.scss
packages/ringcentral-widgets/components/TabContentPanel/index.js
packages/ringcentral-widgets/containers/DialerAndCallsTabContainer/index.js
packages/ringcentral-widgets/containers/DialerAndCallsTabContainer/styles.scss

https://app.zeplin.io/project/59df2e4346294d03f96d15a9/screen/5b2c650bbcf22739360a8b8c

style(DialerPanel, TabContentPanel, DialerAndCallsTabContainer): refine dialer layout

---

packages/ringcentral-integration/modules/Conversations/index.js

fix messages list fetch error

---

packages/ringcentral-widgets/components/ActiveCallPanel/styles.scss
packages/ringcentral-widgets/components/ConferenceParticipantPanel/ParticipantItem.js
packages/ringcentral-widgets/components/ConferenceParticipantPanel/i18n/en-US.js
packages/ringcentral-widgets/components/ConferenceParticipantPanel/index.js
packages/ringcentral-widgets/components/Modal/styles.scss

* Conference has one participant should display "1 participant"
* Mouse on hover avatar area should be clickable( change to pointer)
* https://jira.ringcentral.com/browse/RCINT-8204
* https://jira.ringcentral.com/browse/RCINT-8203

fix(ConferenceParticipantPanel, ActiveCallPanel): refine ConferenceParticipantPanel

---

packages/ringcentral-widgets/components/ActiveCallPanel/styles.scss
packages/ringcentral-widgets/components/ConferenceParticipantPanel/index.js
packages/ringcentral-widgets/components/ConferenceParticipantPanel/styles.scss
packages/ringcentral-widgets/components/Modal/styles.scss
packages/ringcentral-widgets/containers/ConferenceCallDialerPage/index.js
packages/ringcentral-widgets/containers/ConferenceCallDialerPage/styles.scss
packages/ringcentral-widgets/containers/ConferenceParticipantPage/index.js

* align call button on the page
* fix phone number formation 
https://jira.ringcentral.com/browse/RCINT-8207
https://jira.ringcentral.com/browse/RCINT-8210

 fix(ConferenceParticipantPanel): fix issues

---

packages/ringcentral-widgets-demo/dev-server/Phone.js
packages/ringcentral-widgets/containers/ConferenceParticipantPage/index.js

https://jira.ringcentral.com/browse/RCINT-8213

 fix(ConferenceParticipantPage): fix jump logic

---

packages/ringcentral-widgets/components/ActiveCallPanel/ConferenceInfo.js
packages/ringcentral-widgets/components/ActiveCallPanel/styles.scss

using <CallAvatar/> component instead of DIV and background image

refactor(ActiveCallPanel): use <CallAvatar/> as conference info

---

packages/ringcentral-widgets/components/ActiveCallPanel/ConferenceInfo.js
packages/ringcentral-widgets/components/ActiveCallPanel/styles.scss

only avatars are clickable
https://jira.ringcentral.com/browse/RCINT-8231

fix(ActiveCallPanel): shrink call avatar on conference call's click area

---

packages/ringcentral-widgets/components/ActiveCallItem/styles.scss
packages/ringcentral-widgets/components/CallItem/styles.scss

temporary fix the button alignment issue

style(ActiveCallItem, CallItem): ajust button size

---

packages/ringcentral-widgets/components/ActiveCallItem/styles.scss
packages/ringcentral-widgets/components/CallItem/styles.scss

the $fixed-icon-width has impact on history page

revert(ActiveCallItem, CallItem): revert pr #1008

---

packages/ringcentral-widgets/containers/CallsOnholdPage/index.js

after merging, need to route to call ctrl page

fix(CallsOnholdPage): fix router after merging

---

packages/ringcentral-widgets/components/AddCallAlert/index.js

* fix the result that AddCallAlert.handleMessage return

fix: AddCallAler.handleMessage error (#1028)

---

packages/ringcentral-integration/modules/ConferenceCall/getConferenceCallReducer.js

docs(ConferenceCall): Add comments for `getMergingPairReducer`

---

packages/ringcentral-widgets/components/CallsOnholdPanel/index.js
packages/ringcentral-widgets/containers/CallsOnholdPage/index.js

* remove the `contactMapping`
* add `reselect` to improve the props calculation speed

refactor(CallsOnholdPage, CallsOnholdPanel): remove redundant props and import reselector

---

packages/ringcentral-integration/modules/ConferenceCall/index.js
packages/ringcentral-widgets/containers/CallsOnholdPage/index.js

fix(conferenceCall,CallsOnholdPage):when user merge to a recoding call can't do goback

fix(conferenceCall,CallsOnholdPage):when user merge to a recoding call can't do goback

---

packages/ringcentral-widgets/components/ActiveCallPanel/MergeInfo.js

fix(MergeInfo): disable spinner when it is on conference call and fix typo

---

packages/ringcentral-widgets/containers/CallsOnholdPage/index.js
packages/ringcentral-widgets/modules/RouterInteraction/index.js

when there is no active call, clicking the back button will navigate user to the dialer

fix(CallsOnholdPage): fix router

---

packages/ringcentral-widgets/components/ConferenceParticipantPanel/ParticipantItem.js
packages/ringcentral-widgets/components/ConferenceParticipantPanel/styles.scss
packages/ringcentral-widgets/components/MediaObject/index.js
packages/ringcentral-widgets/components/MediaObject/styles.scss

https://css-tricks.com/media-object-bunch-ways/
https://getbootstrap.com/docs/3.3/components/#media
BREAKING CHANGE: refactoring ParticipantItem.js using new component

feat(components): Add <MediaObject/>

---

packages/ringcentral-widgets/components/CallsListPanel/index.js
packages/ringcentral-widgets/components/LogNotification/index.js
packages/ringcentral-widgets/components/SettingsPanel/index.js
packages/ringcentral-widgets/containers/CallsListPage/index.js

Show/Hide log button in `LogNotification` according to flag props `showNotiLogButton`, which default value is `true`. It means normally the button will show, unless you say not.

Show/Hide log button in `LogNotification`

---

packages/ringcentral-widgets/components/ActiveCallItemV2/index.js
packages/ringcentral-widgets/components/ActiveCallPanel/styles.scss

* fix meetings panel sizing issue
* fix `can not get id from undefined`

fix(ActiveCallItemV2, ActiveCallPanel): fix issues

---

packages/ringcentral-widgets-demo/dev-server/Phone.js
packages/ringcentral-widgets-demo/dev-server/containers/App/index.js

for the sake of build, temporary remove the features. Will restore them after update the tests

revert(dev-server): revert RCINT-7940&RCINT-7934 features

---

packages/ringcentral-integration/modules/DetailedPresence/index.js

* Change the method invoking via passing _fetch ref.

fix(DetailedPresence): fix the wrong usage of throttle by fetchRemainingCalls method

---

packages/ringcentral-widgets/components/CallsOnholdPanel/i18n/en-US.js

'No available calls '->'No available calls'

docs(CallsOnholdPanel): remove useless white space

---

packages/ringcentral-integration/integration-test/mock/index.js
packages/ringcentral-integration/modules/ConferenceCall/index.js
packages/ringcentral-widgets-test/package.json
packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/ActiveCallPanel.spec.js
packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/data/conferenceUpdate.json
packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/helper.js
packages/ringcentral-widgets-test/test/support/session.js

rcint-7712 auto test

---

packages/ringcentral-integration/modules/RecentMessages/index.js

_getLocalRecentMessages() got the wrong messages from the voice mail
https://jira.ringcentral.com/browse/RCINT-8371

fix(RecentMessages): fix _getLocalRecentMessages()

---

packages/ringcentral-widgets/components/ActiveCallItemV2/index.js
packages/ringcentral-widgets/components/ActiveCallItemV2/styles.scss

* Should display Accept button in Ringing Call section
* Multiple contact match should remember the selected avatar
https://jira.ringcentral.com/browse/RCINT-8368
https://jira.ringcentral.com/browse/RCINT-8370

fix(ActiveCallItemV2): fix contact matching and ringing call buttons

---

packages/ringcentral-widgets/components/CallAvatar/index.js

fix(CallAvatar): refine the default avatar displaying, fix the random overlap behavior
Related work item: #8369

fix(CallAvatar): refine the default avatar displaying, fix the random overlap behavior

---

packages/ringcentral-widgets-demo/dev-server/containers/App/index.js
packages/ringcentral-widgets/containers/CallCtrlPage/index.js

* add missing parts from ConferenceCallMergeCtrlPage, merged into CallCtrlPage
* use the CallCtrlPage for route /conferenceCall/mergeCtrl in Demo app

fix(CallCtrlPage): complete the merging of CallCtrlPage and ConferenceCallMergeCtrlPage

---

packages/ringcentral-widgets-demo/dev-server/Phone.js
packages/ringcentral-widgets/containers/CallCtrlPage/index.js
packages/ringcentral-widgets/containers/ConferenceParticipantPage/index.js

https://github.com/ringcentral/LyncIntegration/pull/448/files

refactor(CallCtrlPage): remove router logic for `onMerge`

---

packages/ringcentral-widgets/containers/ConversationsPage/index.js

FixBug/shouldn't have C2SMS button when no compose text permission in the conversation list

FixBug/shouldn't have C2SMS button when no compose text permission

---

packages/ringcentral-widgets-demo/dev-server/Phone.js
packages/ringcentral-widgets/components/ActiveCallItemV2/index.js
packages/ringcentral-widgets/components/ActiveCallItemV2/styles.scss
packages/ringcentral-widgets/components/ActiveCallPad/index.js
packages/ringcentral-widgets/components/ContactDisplay/index.js
packages/ringcentral-widgets/containers/CallCtrlPage/index.js

 feat(CallCtrlPage, Phone): add On Hold List Page Jump Logic 

---

packages/ringcentral-integration/modules/Webphone/index.js
packages/ringcentral-widgets-demo/dev-server/Phone.js
packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/ActiveCallPanel.spec.js
packages/ringcentral-widgets-test/test/integration-test/calls/Calls.spec.js
packages/ringcentral-widgets/containers/ActiveCallsPage/index.js
packages/ringcentral-widgets/containers/CallCtrlPage/index.js

refine(CloseMergingPair, Phone, ActiveCallsPage, CallCtrlPage, WebPhone): refactor the closeMergingPair flow
* Move the closeMergingPair in webphone hooks  #RCINT-8297

refine(CloseMergingPair, Phone, ActiveCallsPage, CallCtrlPage, WebPhone): refactor the closeMergingPair flow

---

packages/ringcentral-widgets/components/ConferenceParticipantPanel/index.js

when there are no participants left, show the docs '0 participants' other than '0 participant'

docs(ConferenceParticipantPanel): 0 participants

---

packages/ringcentral-integration/modules/ConferenceCall/index.js

Signed-off-by: Joy Zhang <mint.soda@hotmail.com>

feat RCI-8377 Conference call should be active when merged

---

packages/ringcentral-widgets/containers/ConferenceCallDialerPage/index.js
packages/ringcentral-widgets/containers/DialerPage/index.js
packages/ringcentral-widgets/modules/DialerUI/index.js

* add a callback method in the DialerUI.onCallButtonClick method

fix(ConferenceCallDialerPage, DialerUI): fix a bug in ConferenceCallDialer page sets the mergingPair when the call is not made actually.

---

packages/ringcentral-widgets-test/jest.setup.js
packages/ringcentral-widgets-test/package.json
packages/ringcentral-widgets-test/test/integration-test/CallCtrlPage/ConferenceCallCtrl.spec.js
packages/ringcentral-widgets-test/test/integration-test/CallCtrlPage/CurrentCallCtrl.spec.js
packages/ringcentral-widgets-test/test/integration-test/IncomingCallPage/IncomingCallPad.spec.js
packages/ringcentral-widgets-test/test/integration-test/calls/CallsOnHoldPage.spec.js
packages/ringcentral-widgets-test/test/integration-test/dialer/Dialer.spec.js
packages/ringcentral-widgets-test/test/integration-test/settings/CallingSettings.spec.js
packages/ringcentral-widgets-test/test/integration-test/settings/RegionSettings.spec.js
packages/ringcentral-widgets-test/test/integration-test/webphoneBadge/index.spec.js

1. fix jest timeout error
2. some tests mix up the store when the store is a global varible

fix jest timeout error

---

packages/ringcentral-widgets-demo/dev-server/Phone.js
packages/ringcentral-widgets/containers/IncomingCallPage/index.js

* Answer and Hold Incoming call control should update when current call disconnected
https://jira.ringcentral.com/browse/RCINT-8542

fix(IncomingCallPage, Phone.js): fix ringing page display issues

---

packages/ringcentral-widgets/components/CallItem/index.js

fix bug that conference call will show as Anonymous in call history 

---

packages/ringcentral-widgets/components/ActiveCallPad/index.js

fix(ActiveCallPad): fix more button expantion

---

packages/ringcentral-integration/modules/Webphone/index.js
packages/ringcentral-widgets-demo/dev-server/Phone.js
packages/ringcentral-widgets/components/IncomingCallPanel/index.js
packages/ringcentral-widgets/components/IncomingCallPanel/styles.scss
packages/ringcentral-widgets/containers/IncomingCallPage/index.js

* fix setState() criteria
BREAKING CHANGE: change avatar in <IncomingCallPanel/> with <CallAvatar/>
https://jira.ringcentral.com/browse/RCINT-8542

fix(IncomingCallPage): fix RCINT-8542

---

packages/ringcentral-widgets/components/ActiveCallItemV2/styles.scss

* align call buttons
* change cursor style over the text

style(ActiveCallItemV2): fix styling and layout

---

packages/ringcentral-widgets/containers/DialerAndCallsTabContainer/i18n/en-US.js
packages/ringcentral-widgets/containers/DialerAndCallsTabContainer/index.js

fixbug for sometimes callTab show lowercase

fixbug for standalone opens with lowercase

---

packages/ringcentral-widgets/components/LoginPanel/styles.scss

Modify styles of `LoginButton` and `SignUpButton` in `LoginPanel`.

feat: 🎸 Mod styles of LoginButton & SignUp Button

---

packages/ringcentral-integration/integration-test/mock/index.js
packages/ringcentral-integration/modules/CallMonitor/index.js
packages/ringcentral-integration/modules/ConferenceCall/index.js
packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/ActiveCallPanel.spec.js
packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/data/numberParser.json
packages/ringcentral-widgets-test/test/integration-test/calls/CallsOnHoldPage.spec.js
packages/ringcentral-widgets-test/test/support/session.js
packages/ringcentral-widgets/containers/CallCtrlPage/index.js

RCINT-8402,move the lastCallInfo to conferencecall module

refactor(conferencecall):move the lastCallInfo to conferencecall module

---

packages/ringcentral-widgets/containers/ConferenceCallDialerPage/index.js
packages/ringcentral-widgets/modules/ConferenceDialerUI/actionTypes.js
packages/ringcentral-widgets/modules/ConferenceDialerUI/getReducer.js
packages/ringcentral-widgets/modules/ConferenceDialerUI/index.js
packages/ringcentral-widgets/modules/DialerUI/actionTypes.js
packages/ringcentral-widgets/modules/DialerUI/getReducer.js
packages/ringcentral-widgets/modules/DialerUI/index.js

- isolate DialerUI reducer and action types
- add setLastSessionId func for clear to field when session id changed
- remove useless lastDialedState

Rcint 8654 - apply clear to field strategy

---

packages/ringcentral-widgets/lib/AdapterCore/index.js
packages/ringcentral-widgets/lib/AdapterModuleCore/index.js

fix(AdapterModuleCore,AdapterCore): Locale does not work for locale module is not ready

---

packages/ringcentral-widgets/components/LoginPanel/styles.scss

fix signup button background color not right problem

fix: 🐛 fix windows signup button background color

---

.travis.yml

Trigger google regression release when a push comes

chore: 🤖 Trigger release in google regression branch

---

packages/ringcentral-widgets/components/LoginPanel/styles.scss

fix background color for windows

fix: 🐛 fix signup button bg color for windows

---

packages/ringcentral-widgets/lib/AdapterCore/index.js

When window minimized logo icon and name overlaped

fixbug when minimized logo overlaped

---

packages/ringcentral-widgets-demo/dev-server/containers/MainView/index.js
packages/ringcentral-widgets/containers/DialerAndCallsTabContainer/index.js
packages/ringcentral-widgets/containers/DialerPage/index.js
packages/ringcentral-widgets/lib/hasActiveCalls.js

- unify has active calls logic by adding helper function
- RCINT-8727 - update the detection of has active calls on webTRC mode

unify has active calls logic by adding helper function

---

packages/ringcentral-widgets-demo/dev-server/Phone.js

fix route bug on incoming call disconnected

fix route bug on incoming call disconnected

---

packages/ringcentral-widgets/lib/AdapterCore/index.js
packages/ringcentral-widgets/lib/AdapterModuleCore/index.js

fix(AdapterCore,AdapterModuleCore): should push locale first to init string

---

packages/ringcentral-widgets-demo/dev-server/Phone.js

* fix route bug on incoming call disconnected
* back to /calls when hangup last active session but has ring session

fix route bug on incoming call disconnected (#1306)

---

packages/ringcentral-integration/modules/Webphone/getWebphoneReducer.js
packages/ringcentral-widgets-demo/dev-server/Phone.js
packages/ringcentral-widgets-demo/dev-server/containers/App/index.js
packages/ringcentral-widgets-test/test/integration-test/CallCtrlPage/helper.js
packages/ringcentral-widgets/components/CallCtrlPanel/index.js
packages/ringcentral-widgets/containers/CallBadgeContainer/index.js
packages/ringcentral-widgets/containers/CallCtrlPage/CallCtrlPage.js

* fix found eslint error
* fix found clearSessionCaching action bug
* fix call badge hidden issue
* make CallBadgeContainer passing session id
* make gotoParticipantsCtrl with session id
* '/conferenceCall/participants' is also a page within call ctrl

make some optimizations (#1308)

---

packages/ringcentral-integration/modules/Webphone/index.js
packages/ringcentral-widgets-demo/dev-server/Phone.js

* session object of webphone events argument should not be a new instance
* add tracking session diff
* keep stay on all calls page on call resumre
* add onCallResume instead of session diff

keep stay on all calls page on call resumre (#1320)

---

packages/ringcentral-widgets/components/DatePicker/index.js

fix(Component): fix DatePicker issues [RCINT-8754]

---

packages/phone-number/lib/cleanNumber/index.js
packages/phone-number/lib/extractControls/index.js
packages/phone-number/lib/parse/index.js
packages/phone-number/lib/parse/index.test.js
packages/ringcentral-integration/modules/Call/index.js
packages/ringcentral-integration/modules/Webphone/index.js
packages/ringcentral-widgets-demo/dev-server/containers/App/index.js
packages/ringcentral-widgets/components/ConferencePanel/index.js
packages/ringcentral-widgets/components/TabContentPanel/index.js
packages/ringcentral-widgets/containers/ConferencePage/index.js

* Add extended control parsing, currently only support pause(,)
* Add auto enter host key for instant conferencing, default to disabled

[feature] Add pause (,) support for webphone dialing

---

packages/ringcentral-widgets/lib/AdapterCore/styles.scss

* UI Change: adjust UI in call status bar in floating window
* UI Change: adjust UI in call status bar in floating window
* UI Change: adjust UI in call status bar in floating window

 UI Change: adjust UI in call status bar in floating window (#1336)

---

packages/ringcentral-widgets/components/SmCallControl/styles.scss

style(SmallCallControl): add SVG height to adapt IE11

---

.prettierrc

Add `.prettierrc` file for better code formatting experience.

style: 💄 Add prettier config for better formatting

---

packages/ringcentral-e2e-test/e2e.config.js
packages/ringcentral-e2e-test/src/lib/accountManager/index.js
packages/ringcentral-e2e-test/src/lib/webphone/index.js
packages/ringcentral-e2e-test/src/steps/salesforce/outboundCall.js
packages/ringcentral-e2e-test/src/steps/salesforce/toggleEnv.js

add change env(xmnup/itl)

---

packages/ringcentral-integration/modules/CallLogger/getDataReducer.js
packages/ringcentral-integration/modules/CallLogger/index.js

fix(CallLogger): Add transferMiddleNumber property in call when transfer

---

packages/ringcentral-widgets-demo/dev-server/containers/App/index.js
packages/ringcentral-widgets-test/test/integration-test/history/Calls.spec.js
packages/ringcentral-widgets/components/ActionMenu/index.js
packages/ringcentral-widgets/components/CallItem/index.js
packages/ringcentral-widgets/components/CallList/index.js
packages/ringcentral-widgets/components/CallListV2/index.js
packages/ringcentral-widgets/components/CallsListPanel/index.js
packages/ringcentral-widgets/components/NoCalls/index.js
packages/ringcentral-widgets/components/SlideMenu/index.js
packages/ringcentral-widgets/components/SlideMenu/styles.scss

Refactor some issues with CallsListV2 and also disabled the menu animation when V2 is used.

refactor(CallsList): Refactor CallsListV2

---

packages/ringcentral-e2e-drivers/src/puppeteer/index.js
packages/ringcentral-e2e-test/src/features/salesforce/ActiveCalls/RCI-1122.js

add driverApi to support attribute。

add driverApi to support attribute

---

packages/ringcentral-widgets/lib/hasActiveCalls.js

when under webphone mode, using callMonitor.otherDeviceCalls.length and webphone.sessions.length

fix(hasActivecalls): change logic

---

packages/ringcentral-integration/lib/contactHelper.js

fix(contactHelper): recorrecting personal contact phone type

---

packages/ringcentral-widgets/components/ConferenceParticipantPanel/styles.scss
packages/ringcentral-widgets/components/MessageItem/styles.scss

https://jira.ringcentral.com/browse/RCINT-9051

style(MessageItem, ParticipantItem): refine style

---

packages/ringcentral-widgets/components/CallsListPanel/index.js

Update zendesk 2.0.2 regression

---

packages/ringcentral-integration/modules/CallLogger/index.js

fix(Calllogger): Add phoneNumberUpdated value to check if number updated

---

packages/ringcentral-e2e-test/src/features/Common/SMS/RCI-576_Send_text_message_on_compose_text_page.spec.js
packages/ringcentral-e2e-test/src/steps/commons/login.js
packages/ringcentral-e2e-test/src/steps/commons/logout.js
packages/ringcentral-e2e-test/src/steps/commons/navigateToSettings.js
packages/ringcentral-e2e-test/src/steps/commons/toggleEnv.js

1. add logout step 
2. modify login step 
3. modify toggleEnv logic

test: use realLogin

---

packages/ringcentral-widgets-demo/dev-server/containers/App/index.js
packages/ringcentral-widgets/components/CallCtrlPanel/index.js
packages/ringcentral-widgets/components/TransferPanel/index.js
packages/ringcentral-widgets/containers/ActiveCallsPage/index.js
packages/ringcentral-widgets/containers/CallCtrlPage/CallCtrlContainer.js
packages/ringcentral-widgets/containers/CallCtrlPage/index.js
packages/ringcentral-widgets/containers/SimpleActiveCallCtrlPage/index.js
packages/ringcentral-widgets/containers/TransferPage/index.js

BREAKING CHANGE: Need to add or update transfer page router to /transfer/:sessionId(/:type)
RELATED ISSUE: #1148

refactor(CallCtrlPage,TransferPage): Split transfer page from call ctrl panel

---

packages/ringcentral-widgets/components/NavigationBar/index.js
packages/ringcentral-widgets/components/NavigationBar/styles.scss
packages/ringcentral-widgets/components/TabNavigationButton/index.js
packages/ringcentral-widgets/components/TabNavigationView/index.js
packages/ringcentral-widgets/components/TabNavigationView/styles.scss

* Add a new position:'left' in NavigationView's navigationPosition property, to enable navigation bar placed in the left side

feat(NavigationView): add left-side(vertical) position support for navigation bar

---

packages/ringcentral-integration/modules/ActiveCallControl/index.js

ActiveCallControl: getDataParty

fix(ActiveCallControl): Enhance

---

packages/ringcentral-widgets/components/CallItem/index.js
packages/ringcentral-widgets/components/SlideMenu/index.js

Improve the calllist v2 item issue

feat(Zendesk): Fix callitem issue in CallListV2
