gulpfile.js
set package name when publish to npm
release to lastest use ringcentral-js-widget
release to npm use ringcentral-widget
=> set package name when publish to npm

package.json, src/components/ComposeTextPanel/i18n/en-US.js, src/components/ComposeTextPanel/index.js, src/components/ComposeTextPanel/styles.scss, src/components/RecipientsInput/styles.scss, src/containers/ComposeTextPage/index.js
* adjust compose text ui
* jump to conversation page when message sender return one response
* jump to messages page when message sender return multiple responses
ready for review @LingForCC
=> adjust compose text ui and redirect url

dev-server/Phone.js, package.json, src/components/CallingSettingsAlert/i18n/en-US.js, src/components/CallingSettingsAlert/index.js, src/components/WebphoneAlert/i18n/en-US.js, src/components/WebphoneAlert/index.js, yarn.lock
enhancement of calling settings.
=> enhancement of calling settings

dev-server/Phone.js, dev-server/containers/App/index.js, src/components/ActiveCallPanel/index.js, src/components/ActiveCallPanel/styles.scss, src/components/ContactDisplay/index.js, src/components/FormattedMessage/index.js, src/components/IncomingCallPanel/index.js, src/components/IncomingCallPanel/styles.scss, src/containers/ActiveCallPage/index.js
show contact name in active call page
=> show contact name in active call page

src/components/CallingSettingsPanel/i18n/en-US.js, src/components/CallingSettingsPanel/index.js, src/components/CallingSettingsPanel/styles.scss
=> enhancement tooltip ui

packages/ringcentral-widgets/components/CallItem/styles.scss
Fix the issue where the scrollbar is under call item element in safari, this is a known issue for Safari. The PR is a workaround to resolve this issue in our situation by removing background color of call item.
=> bugfix: a workaround to solve the scrollbar issue in safari

packages/ringcentral-integration/modules/Analytics/index.js
1. Make tracking list can append more methods from the child class.
2. Add routes for tracking - /calls.
=> Make tracking list can append more methods from the child class

packages/ringcentral-widgets/components/VoicemailPlayer/index.js
=> [JIRA-7864] Navigation bar doesn't work on IE 11

packages/ringcentral-integration/modules/Subscription/index.js
there is chance that the this._subscription would be set to null and in the evt listners they still
call the this._subscription.subscription()
http://ec2-13-124-226-35.ap-northeast-2.compute.amazonaws.com/sentry/skypeforbusiness/issues/481/
=> fix(Subscription): fix subscription' of null

packages/ringcentral-widgets/components/MeetingPanel/index.js
=> fix array fill

packages/ringcentral-integration/modules/ConferenceCall/getConferenceCallReducer.js, packages/ringcentral-integration/modules/ConferenceCall/index.js, packages/ringcentral-widgets/containers/ActiveCallsPage/index.js, packages/ringcentral-widgets/containers/CallCtrlPage/index.js, packages/ringcentral-widgets/containers/CallsOnholdPage/index.js
since sip instance can not be serialized and tossing around throught workers, then we need to record
the sessionId to do the trick
BREAKING CHANGE: 
* refresh the avatar url when merging
* recording session id instead of sip instance
https://jira.ringcentral.com/browse/RCINT-8072
=> refactor(ConferenceCall, ActiveCallsPage, CallCtrlPage, CallsOnholdPage): conference.session->conference.sessionId

packages/ringcentral-widgets-demo/dev-server/Phone.js, packages/ringcentral-widgets-demo/dev-server/containers/App/index.js, packages/ringcentral-widgets/containers/CallCtrlPage/index.js
On file CllCtrlPage/index.js, we used "routerInteraction.replace(`${routerInteraction.currentPath}/${sessionId}`);" to avoid flickering when merging. Now the issue has gone, so remove it.
BREAKING CHANGE:
* Phone.js: indexOf->=== for conferece call routers
* App:
* /calls/active(/:sessionId) -> /calls/active
* /conferenceCall/mergeCtrl(/:sessionId) -> /conferenceCall/mergeCtrl
=> refactor(CallCtrlPage, dev-server): remove router.replace() when merging

packages/ringcentral-widgets-demo/dev-server/containers/App/index.js, packages/ringcentral-widgets/components/ActiveCallPanel/MergeInfo.js, packages/ringcentral-widgets/components/ActiveCallPanel/index.js, packages/ringcentral-widgets/components/CallCtrlPanel/index.js, packages/ringcentral-widgets/containers/CallCtrlPage/index.js, packages/ringcentral-widgets/containers/ConferenceCallMergeCtrlPage/index.js
Since we have the file ConferenceCallMergeCtrlPage, then we can make it as HOC to store the
onLastCallEnded(), and remove unrelated code out of CallCtrlPage component
BREAKING CHANGE:
* make ConferenceCallMergeCtrlPage as HOC
=> refactor(ActiveCallPanel, CallCtrlPanel, CallCtrlPage, ConferenceCallMergeCtrlPage, App): extract logic into HOC

packages/ringcentral-integration/modules/CallMonitor/index.js, packages/ringcentral-widgets/components/ActiveCallList/index.js
Because we filtering out the conference call when merging, so the lastCallInfo selector won't get
the conference call
https://jira.ringcentral.com/browse/RCINT-8087
=> fix(CallMonitor, ActiveCallList): fix 'Disconnected' when merging into conference

packages/ringcentral-integration/modules/ConferenceCall/index.js
Because ContactMatcher is optional, then in bringInToConference() and _getProfile(), we need to
check the existence of the module
=> refactor(ConferenceCall): defending when no ContactMatcher

packages/ringcentral-integration/modules/Webphone/getWebphoneReducer.js, packages/ringcentral-integration/modules/Webphone/index.js, packages/ringcentral-widgets/components/ActiveCallPanel/MergeInfo.js
When merging an onhold active call on merge control page, the old logic will preserve the active
session id as the cached call's id, we need to update it when clear the caching.
BREAKING CHANGE: add sessions into clearSessionCaching() and add `clearSessionCaching` action into
getActiveSessionIdReducer()
=> fix(WebPhone, ActiveCallPanel): fix blank page

packages/ringcentral-widgets/components/CallAvatar/index.js, packages/ringcentral-widgets/package.json, yarn.lock
When the URL is written in base64 or blob style, set them to the <img/> directly.
BREAKING CHANGE: Add 'is-base64'
=> feat(CallAvatar): show img when url is base64/blob

packages/ringcentral-widgets/components/ActiveCallPanel/MergeInfo.js
- [8148] Bugfix
Only show the loading when it is not conference call and the lastCallInfo.name/phonenumber is not ready
- Refactor
Refactor the logic and handle the timeout cleanup
=> [RCINT-8274] fix bug that the loading text is displaying when it is on conference call in simplified call control page

packages/ringcentral-integration/modules/Webphone/index.js
activeSession should always stick to activeSessionId
=> refactor webphone activeSession

packages/ringcentral-widgets/containers/ConferenceCallMergeCtrlPage/index.js
if the last has already been terminated after rendering, need to trigger the callback at the point
=> fix(ConferenceCallMergeCtrlPage): check and trigger the router after mounting

packages/ringcentral-widgets/components/CallAvatar/index.js
Because in sfb, we can only get avatar of sfb contacts in base64 formation in C#(still can transform
it to blob in renderer process, but for the sake of performance, we don't do that), so add the
base64 support
=> feat(CallAvatar): add base64 support

packages/ringcentral-widgets/components/ActiveCallItem/index.js, packages/ringcentral-widgets/components/ActiveCallItem/styles.scss, packages/ringcentral-widgets/components/ActiveCallList/index.js, packages/ringcentral-widgets/components/ActiveCallsPanel/index.js, packages/ringcentral-widgets/containers/ActiveCallsPage/index.js, packages/ringcentral-widgets/containers/ConferenceParticipantPage/index.js
[Remove the merge button from All Calls tab](https://jira.ringcentral.com/browse/RCINT-7934)
=> refactor(ActiveCallPage): remove merge button

packages/ringcentral-widgets-demo/dev-server/containers/App/index.js
=> hotfix(App): temporarily revert the last change for /conferenceCall/mergeCtrl route component, since it is not stable to use

packages/ringcentral-widgets-demo/dev-server/Phone.js, packages/ringcentral-widgets-demo/dev-server/containers/App/index.js, packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/ActiveCallPanel.spec.js, packages/ringcentral-widgets/components/ActiveCallPad/styles.scss, packages/ringcentral-widgets/containers/CallCtrlPage/index.js
fix the issue when open on-hold call in calls tab that still sees the previous merging call
* add a switch in CallCtrlPage to control use multiple layouts supporting
=> fix(CallCtrlPage): fix the issue when open on-hold call in calls tab that still sees the previous merging call

packages/ringcentral-widgets/components/ConversationsPanel/index.js, packages/ringcentral-widgets/components/MessageItem/index.js
If the user is only pager account, for the phone number which not internal number should disable the Click-To-SMS icon in messages page action menu list.
=> FixBug/ [RCINT-8384]Some SMS Log UI problem when account belongs to specific brands or without SMS nor Pager permission.

packages/ringcentral-integration/modules/ConferenceCall/index.js, packages/ringcentral-widgets-demo/dev-server/Phone.js, packages/ringcentral-widgets-demo/dev-server/containers/App/index.js, packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/ActiveCallPanel.spec.js, packages/ringcentral-widgets/containers/CallCtrlPage/index.js, packages/ringcentral-widgets/containers/CallsOnholdPage/index.js, packages/ringcentral-widgets/containers/ConferenceCallDialerPage/index.js
* Change the /conferencecall/dialer router template from "/conferenceCall/dialer/:fromNumber" to
path="/conferenceCall/dialer/:fromNumber/:fromSessionId"
* refine the way to call setMergingPair, only at call button clicked
#RCINT-8432
=> fix(ConferenceCall,CallCtrlPage): fix the issue about conference call dialer page doesn't handle mergingPair correctly

packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/ActiveCallPanel.spec.js
test(activecallpanel) :use simulate click instead of props's func
=>  test(activecallpanel) :use simulate click instead of props's func

packages/ringcentral-widgets/containers/DialerAndCallsTabContainer/index.js
Since we showing the call items in all calls page by presence API, then we should show tabs by the same design
=> refactor(DialerAndCallsTabContainer): judge `applicable` by callMonitor

packages/ringcentral-widgets/components/ActiveCallItem/index.js, packages/ringcentral-widgets/components/ActiveCallItemV2/index.js, packages/ringcentral-widgets/components/ActiveCallPanel/CallInfo.js, packages/ringcentral-widgets/components/ActiveCallPanel/ConferenceInfo.js, packages/ringcentral-widgets/components/ActiveCallPanel/MergeInfo.js, packages/ringcentral-widgets/components/CallAvatar/index.js, packages/ringcentral-widgets/components/CallAvatar/styles.scss, packages/ringcentral-widgets/components/ConferenceParticipantPanel/ParticipantItem.js, packages/ringcentral-widgets/components/ConfirmMergeModal/index.js
* remove `shouldBubbleClick`
* add `className` & `onClick`
BREAKING CHANGE: remove `shouldBubbleClick` on other components
=> fix(CallAvatar): remove `shouldBubbleClick`

packages/ringcentral-integration/modules/Webphone/index.js, packages/ringcentral-widgets-demo/dev-server/Phone.js
* Handle the answer method to avoid duplicate Accepting call actions which leads an error that can end the call
* Related work item: #RCINT-8631
=> fix(Webphone): fix the :bug: when double-click on answer button in coming page, it won't navigate to call control page

packages/ringcentral-widgets/components/ActiveCallPanel/ConferenceInfo.js, packages/ringcentral-widgets/components/ActiveCallPanel/styles.scss
=> feat(ConferenceInfo): 🚀 improve the ConferenceInfo component to display different amount of avatars when the window resizing.  #RCINT-8622

packages/ringcentral-integration/modules/CallMonitor/index.js, packages/ringcentral-widgets/containers/CallCtrlPage/index.js
* Refine the logic onAdd method in CallCtrlPage
#RCINT-8649 (Given 1 hold call and 1 active incoming call, when clicking the Add button from the on-hold call ctrl page, it will not redirect to the simplified call ctrl dialer page)
=> fix(CallCtrlPage, CallMonitor): 🐛 fix a bug in onAdd method in CallCtrlPage

packages/ringcentral-widgets-test/test/integration-test/CallCtrlPage/ConferenceCallCtrl.spec.js, packages/ringcentral-widgets-test/test/integration-test/CallCtrlPage/helper.js, packages/ringcentral-widgets-test/test/integration-test/ConferenceCall/flow.spec.js, packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/ActiveCallPanel.spec.js, packages/ringcentral-widgets-test/test/integration-test/IncomingCallPage/IncomingCallPad.spec.js, packages/ringcentral-widgets-test/test/integration-test/calls/Calls.spec.js, packages/ringcentral-widgets-test/test/integration-test/calls/helper.js, packages/ringcentral-widgets-test/test/support/callHelper.js, packages/ringcentral-widgets-test/test/support/session.js
1. getInboundCall function
Inbound Call/Incoming Call Session do not have callId
2. when it comes to execute "phone.webphone.hold"
it is an asynchronous function, need to add await
3. add timeout after simulate action for flow.spec.js IncomingCallPad.spec.js
=> fix(CallCtrlPage/helper.js, callHelper): Session do not have callId in getInboundCall

packages/ringcentral-integration/modules/UserGuide/index.js
GET http://localhost:8080/undefined 404 (Not Found)
=> fix UserGuide module image request error

packages/ringcentral-integration/modules/Webphone/getWebphoneReducer.js, packages/ringcentral-integration/modules/Webphone/index.js, packages/ringcentral-widgets-demo/dev-server/Phone.js, packages/ringcentral-widgets-test/test/integration-test/CallCtrlPage/ConferenceCallCtrl.spec.js, packages/ringcentral-widgets-test/test/integration-test/CallCtrlPage/CurrentCallCtrl.spec.js, packages/ringcentral-widgets-test/test/integration-test/ConferenceCall/flow.spec.js, packages/ringcentral-widgets-test/test/integration-test/ConferenceCallDialerPage/ActiveCallPanel.spec.js, packages/ringcentral-widgets-test/test/integration-test/IncomingCallPage/IncomingCallPad.spec.js, packages/ringcentral-widgets-test/test/integration-test/IncomingCallPage/index.spec.js, packages/ringcentral-widgets-test/test/integration-test/calls/AllCalls.spec.js, packages/ringcentral-widgets/containers/IncomingCallPage/index.js
- RCINT-8630 fix wrong call control display on answering incoming call when there has active call
- optimizie webphone module, remove _beforeCallStart related
- format code of getWebphoneReducer.js
=> RCINT-8630 fix wrong call control display on answering incoming call when there has active call

packages/ringcentral-widgets/components/ActiveCallsPanel/index.js, packages/ringcentral-widgets/components/ActiveCallsPanel/styles.scss, packages/ringcentral-widgets/containers/DialerAndCallsTabContainer/index.js
1. Move notification back.
2. Add an onEnter hook to the nav-container of all-calls tab.
=>  Move notification back

packages/ringcentral-widgets/components/CallCtrlPanel/index.js
hide call control overlap components (KeypadPanel/FlipPanel/TransferPanel/MergeConfirm) on call changed
=> hide call control overlap components on call changed

packages/ringcentral-integration/modules/CallMonitor/index.js, packages/ringcentral-widgets-demo/dev-server/containers/App/index.js, packages/ringcentral-widgets/containers/ActiveCallsPage/index.js, packages/ringcentral-widgets/containers/IncomingCallPage/index.js
* Add logic to remove the mergingPair when answer the incoming call in IncomingCallPage and ActiveCallsPage
=> fix(IncomingCallPage, ActiveCallsPage):  🐛 fix a bug that the mergingPair is not removed when the inbound call is answered

packages/ringcentral-widgets/components/DropdownNavigationView/styles.scss, packages/ringcentral-widgets/components/TabNavigationView/index.js, packages/ringcentral-widgets/components/TabNavigationView/styles.scss
The dropdown menu of TabNavigationView should not be blocked by tab content's SpinnerOverlay.
=> fix(TabNavigationView): TabNavigationView DropdownMenu z-index update

packages/ringcentral-integration/enums/phoneTypes.js, packages/ringcentral-integration/modules/AccountContacts/index.js, packages/ringcentral-widgets/components/ContactDetails/i18n/de-DE.js, packages/ringcentral-widgets/components/ContactDetails/i18n/en-AU.js, packages/ringcentral-widgets/components/ContactDetails/i18n/en-CA.js, packages/ringcentral-widgets/components/ContactDetails/i18n/en-GB.js, packages/ringcentral-widgets/components/ContactDetails/i18n/en-US.js, packages/ringcentral-widgets/components/ContactDetails/i18n/es-419.js, packages/ringcentral-widgets/components/ContactDetails/i18n/es-ES.js, packages/ringcentral-widgets/components/ContactDetails/i18n/fr-CA.js, packages/ringcentral-widgets/components/ContactDetails/i18n/fr-FR.js, packages/ringcentral-widgets/components/ContactDetails/i18n/it-IT.js, packages/ringcentral-widgets/components/ContactDetails/i18n/ja-JP.js, packages/ringcentral-widgets/components/ContactDetails/i18n/pt-BR.js, packages/ringcentral-widgets/components/ContactDetails/i18n/zh-CN.js, packages/ringcentral-widgets/components/ContactDetails/i18n/zh-HK.js, packages/ringcentral-widgets/components/ContactDetails/i18n/zh-TW.js, packages/ringcentral-widgets/components/ContactDetails/index.js, packages/ringcentral-widgets/lib/phoneTypeNames/en-US.js
* remove hard coding direct lable on contact detail page
* repalce AccountContacts with phoneTypes
* add more phone type to ContactDetails.js
BREAKING CHANGE: Show all the phones with corresponding type name on contact detail page
=> refactor(ContactDetails, AccountContacts): using PhoneTypes.js & PhoneTypeNames.js

packages/ringcentral-integration/modules/Conversations/index.js
It happens when lazy loading to fetch data with wrong size.
=> fixbug:it happens when fetch messages with n*pagesize-1,wrong

packages/ringcentral-widgets/lib/hasActiveCalls.js
Since the  callLogSection.showNotification is slower than the webRTC signals, tht tab would
disappear and reappear and disappear again.
https://jira.ringcentral.com/browse/RCINT-9003
=> fix(hasActiveCalls.js): fix bool logic

packages/ringcentral-widgets/components/CallListV2/index.js, packages/ringcentral-widgets/components/CallsPanel/index.js, packages/ringcentral-widgets/containers/CallHistoryPage/index.js
Refactored `CallHisotyPage` and `CallsPanel` modules.
1. `CallHistoryPage` named not right originally as `CallsPage`.
2. Add condition to use `CallList` or `CallListV2` module.
=> feat(Refactor `CallHistoryPage`, `CallsPanel` module):

packages/ringcentral-integration/modules/Conversations/getReducer.js, packages/ringcentral-integration/modules/Conversations/getReducer.test.js, packages/ringcentral-integration/modules/Conversations/index.js
when loading next page, if filteredConversations'length is longer than displayable list'length should increase the current page.
And add a condition to judge whether it is necessary to increase the current page after fetching old conversations success.
fix #9068
=> fix(Conversations): fix conversations list load next page logic

packages/ringcentral-widgets/components/CallListV2/index.js
When there are no calls, related view did not show up. Fixed this problem by adding `noRowsRender` property for `List` in react-virtualized.
=> fix(Fix:View for 0-calls not show):

packages/ringcentral-widgets/components/SettingsPanel/index.js
fix: Toggle and c2d about 'click to dial' should exist when user just has one of the webrtc and ringout permission
=> fix: Toggle and c2d about 'click to dial' should exist when user just has one of the webrtc and ringout permission 
